//! Generates the typed Domains API client from the vendored OpenAPI 3.0 spec.
//!
//! The spec (`openapi/domains.oas3.json`) is committed and merges the v3
//! Domain Lifecycle Management API with the one v1 operation v3 doesn't yet
//! serve (`agreements`). It's regenerated by `cargo run -p generate-api-catalog`
//! at the workspace root (`domains_merge.rs`), not by anything in this crate —
//! this build step just reads the committed file and is hermetic; it never
//! touches the network.

use std::{env, fs, path::Path};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let spec_path = "openapi/domains.oas3.json";
    println!("cargo:rerun-if-changed={spec_path}");
    println!("cargo:rerun-if-changed=build.rs");

    let spec_text = fs::read_to_string(spec_path)?;
    let spec: openapiv3::OpenAPI = serde_json::from_str(&spec_text)?;

    // Builder interface: each operation gets a fluent builder with named setters
    // (e.g. `client.suggest().query(..).limit(..).send()`) instead of positional
    // args, so call sites read clearly without an IDE and unused optional params
    // are simply omitted rather than passed as `None`.
    let mut settings = progenitor::GenerationSettings::new();
    settings.with_interface(progenitor::InterfaceStyle::Builder);
    // Derive `schemars::JsonSchema` on the generated response/request types so
    // the CLI can register them via `CommandSpec::with_json_schema::<T>()` and
    // surface their fields through `--schema`.
    settings.with_derive("schemars::JsonSchema");
    let mut generator = progenitor::Generator::new(&settings);
    let tokens = generator.generate_tokens(&spec)?;
    let ast = syn::parse2(tokens)?;
    let formatted = prettyplease::unparse(&ast);

    let out_dir = env::var("OUT_DIR")?;
    fs::write(Path::new(&out_dir).join("codegen.rs"), formatted)?;
    Ok(())
}
