name: CICD
on: 
  push:
    branches:
      - 'main'
  pull_request:
    branches:
     - '*'

jobs:
  cicd:
    runs-on: ubuntu-latest
    concurrency: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2

      - name: Setup pnpm
        uses: pnpm/action-setup@v6.0.5

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libsecret-1-dev build-essential python3

      - name: Setup Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build CLI
        run: pnpm run build

      - name: Type check
        run: pnpm run check

      - name: Run tests
        run: pnpm test
